server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: editor-design
        uri: lb://editor-design
        predicates:
        - Path=/mveditor/**
        filters:
        - RewritePath=/design/(?<path>.*), /$\{path}
      - id: editor-executor
        uri: lb://editor-executor
        predicates:
        - Path=/mveditor/api/**
        filters:
        - RewritePath=/executor/(?<path>.*), /$\{path}